name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Install Capacitor CLI
        run: npm i -g @capacitor/cli@5

      - name: Build web
        run: npm run build

      - name: Add Android platform
        run: npx cap add android

      - name: Sync web assets
        run: npx cap sync android

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Copy Android config files
        run: |
          if [ -f "android-config/AndroidManifest.xml" ]; then
            mkdir -p android/app/src/main
            cp android-config/AndroidManifest.xml android/app/src/main/AndroidManifest.xml
          fi

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate debug keystore
        run: |
          mkdir -p android/app
          keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: List android directory
        run: ls -la android/

      - name: Build APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace

      - name: List build outputs
        run: |
          find android -name "*.apk" -type f || echo "No APK files found"
          ls -la android/app/build/outputs/ || echo "outputs directory not found"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EcoMeasure-APK
          path: android/app/build/outputs/apk/debug/*.apk 